run:
  concurrency: 16
  timeout: 5m
  tests: false
  allow-parallel-runners: true

linters-settings:
  funlen:
    lines: 180
    statements: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
      - style
  gocyclo:
    min-complexity: 16
  goimports:
    local-prefixes: github.com/sentinel-official/dvpn-node

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    #- dupl
    - errcheck
    - funlen
    #- gochecknoglobals
    #- gochecknoinits
    #- gocognit
    #- goconst
    #- gocritic
    #- gocyclo
    - godot
    - godox
    #- goerr113
    - gofmt
    - goimports
    - golint
    #- gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    #- nestif
    #- nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    #- wsl